### ISSUE TITLE
Make tests compatible for 2.7

### ISSUE THREAD

**Issue by claudiulodro** [woocommerce/wc-e2e-page-objects#1]
The tests currently fail all over the place running WooCommerce 2.7. They need to be brought up to date so that the suite can be used for testing WooCommerce 2.8 when it's released.

Progress on this is in the "update" branch: https://github.com/woocommerce/wc-e2e-page-objects/tree/update

**Comment by gedex** [comment]
Thanks for bringing up this.

**Comment by gedex** [comment]
Fixed in #8.
